name: antoinette
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  smooth_page_indicator: ^1.2.0+3
  email_validator: ^3.0.0
  pin_code_fields: ^8.0.1
  image_picker: ^1.1.2
  dotted_border: ^2.1.0
  intl: ^0.20.2
  get: ^4.7.2
  carousel_slider: ^5.0.0
  syncfusion_flutter_datepicker: ^28.2.9
  pie_chart: ^5.4.0
  camera: ^0.11.1
  http: ^1.3.0
  logger: ^2.5.0
  get_storage:
  google_sign_in: ^6.3.0
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  flutter_facebook_auth: ^7.1.1
  audioplayers: ^6.4.0
  flutter_html: ^3.0.0
  table_calendar: ^3.2.0
  gradient_borders: ^1.0.1
  simple_gradient_text: ^1.3.0
  webview_flutter: ^2.0.3
  mime: ^2.0.0
  pdf: ^3.11.3
  path_provider: ^2.1.5
  open_file: ^3.5.10
  flutter_background_service: ^5.1.0
  socket_io_client: ^3.1.0+2
  location: ^8.0.0
  permission_handler: ^12.0.0+1
  geocoding: ^3.0.0
  shimmer: ^3.0.0
  change_app_package_name: ^1.5.0
  printing: ^5.14.2
  
 
 
  
  

  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # example:
  fonts:
    - family: Flatlion Personal
      fonts:
        - asset: assets/fonts/FlatlionPersonalUse-ALZep.otf
          weight: 400
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
    - family: Cormorant Garamond
      fonts:
        - asset: assets/fonts/CormorantGaramond-VariableFont_wght.ttf
          weight: 400
    - family: Caveat
      fonts:
        - asset: assets/fonts/Caveat-VariableFont_wght.ttf
          weight: 400
          
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
