// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT_4g3y82mxF7nK_d6JHpHyeIRsFN5Zrg',
    appId: '1:300445513181:web:fda64cd03e536662cbb234',
    messagingSenderId: '300445513181',
    projectId: 'dear-henrietta',
    authDomain: 'dear-henrietta.firebaseapp.com',
    storageBucket: 'dear-henrietta.firebasestorage.app',
    measurementId: 'G-41PK09GVYC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxPfKGB4s5lgIRE-jtKdfdt4ufU-HarLM',
    appId: '1:300445513181:android:52f28dce93cc7d9acbb234',
    messagingSenderId: '300445513181',
    projectId: 'dear-henrietta',
    storageBucket: 'dear-henrietta.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcaDzGV7j_vZj7URPWwovPkpddic4xeto',
    appId: '1:300445513181:ios:5ade22a4d6e4a64dcbb234',
    messagingSenderId: '300445513181',
    projectId: 'dear-henrietta',
    storageBucket: 'dear-henrietta.firebasestorage.app',
    iosBundleId: 'com.antoinette.antoinette',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcaDzGV7j_vZj7URPWwovPkpddic4xeto',
    appId: '1:300445513181:ios:1ab7b1f644e8ca50cbb234',
    messagingSenderId: '300445513181',
    projectId: 'dear-henrietta',
    storageBucket: 'dear-henrietta.firebasestorage.app',
    iosBundleId: 'com.example.antoinette',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCT_4g3y82mxF7nK_d6JHpHyeIRsFN5Zrg',
    appId: '1:300445513181:web:cc4c2254b097013bcbb234',
    messagingSenderId: '300445513181',
    projectId: 'dear-henrietta',
    authDomain: 'dear-henrietta.firebaseapp.com',
    storageBucket: 'dear-henrietta.firebasestorage.app',
    measurementId: 'G-97BT22LHL5',
  );
}
