// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjmE8ARZZwIoQFMfnKa7ynGdcp0r-phcA',
    appId: '1:607906174839:web:11aa475c78bbbff2907372',
    messagingSenderId: '607906174839',
    projectId: 'dear-henrietta-a31cb',
    authDomain: 'dear-henrietta-a31cb.firebaseapp.com',
    storageBucket: 'dear-henrietta-a31cb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArB2NVFyXCFV4KwUm7GPI7t-lOeb2k2pA',
    appId: '1:607906174839:android:e486da9544aa589b907372',
    messagingSenderId: '607906174839',
    projectId: 'dear-henrietta-a31cb',
    storageBucket: 'dear-henrietta-a31cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmwZOp3M3TD10tTjLrPE2BVmBX4xIblpA',
    appId: '1:607906174839:ios:d112ffce98d774c6907372',
    messagingSenderId: '607906174839',
    projectId: 'dear-henrietta-a31cb',
    storageBucket: 'dear-henrietta-a31cb.firebasestorage.app',
    iosBundleId: 'com.antoinette.antoinette',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmwZOp3M3TD10tTjLrPE2BVmBX4xIblpA',
    appId: '1:607906174839:ios:a130a278ea39a6e3907372',
    messagingSenderId: '607906174839',
    projectId: 'dear-henrietta-a31cb',
    storageBucket: 'dear-henrietta-a31cb.firebasestorage.app',
    iosBundleId: 'com.example.antoinette',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjmE8ARZZwIoQFMfnKa7ynGdcp0r-phcA',
    appId: '1:607906174839:web:915c8aebccbe6d4a907372',
    messagingSenderId: '607906174839',
    projectId: 'dear-henrietta-a31cb',
    authDomain: 'dear-henrietta-a31cb.firebaseapp.com',
    storageBucket: 'dear-henrietta-a31cb.firebasestorage.app',
  );

}